name: Node.js Package

on:
    push:
      branches: 
         - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
   

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
 
      - run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@ffalpha'

      - run: echo registry=https://npm.pkg.github.com/ffalpha >> .npmrc
      - run: npm publish --registry=https://npm.pkg.github.com/ 
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUBTOKEN}}